import type { AccessLevel, Capability, MenuKey, Role } from './role.model';

const CLIENT_ALL_MENUS: MenuKey[] = [
  'dashboard',
  'inbox',
  'contacts',
  'flows',
  'templates',
  'campaigns',
  'reports',
  'teams',
  'users',
  'roles',
  'quickReplies',
  'settings',
  'billing',
  'audit',
  'developer',
  'profile',
];

const PLATFORM_ALL_MENUS: MenuKey[] = [
  'dashboard',
  'clients',
  'plans',
  'subscriptions',
  'invoices',
  'users',
  'roles',
  'analytics',
  'metaConfig',
  'health',
  'announcements',
  'audit',
  'profile',
];

/**
 * Seeded straight from the PRD §6.3 RBAC matrix (Admin / Supervisor / Agent) and
 * Business §4.4 (platform owner vs operations). Editable at runtime, which is
 * exactly what the Roles & Menus page writes to.
 */
function capabilities(
  entries: [Capability, AccessLevel][],
): Partial<Record<Capability, AccessLevel>> {
  return Object.fromEntries(entries);
}

export const SEED_ROLES: Role[] = [
  {
    id: 'role-admin',
    name: 'Workspace Administrator',
    description: 'Owns the client workspace: WhatsApp connection, billing, staff and automation.',
    scope: 'client',
    menus: CLIENT_ALL_MENUS,
    capabilities: capabilities([
      ['dashboard.view', 'full'],
      ['inbox.view', 'full'],
      ['inbox.reply', 'full'],
      ['inbox.assign', 'full'],
      ['contacts.view', 'full'],
      ['contacts.manage', 'full'],
      ['contacts.export', 'full'],
      ['flows.view', 'full'],
      ['flows.manage', 'full'],
      ['templates.view', 'full'],
      ['templates.manage', 'full'],
      ['campaigns.view', 'full'],
      ['campaigns.manage', 'full'],
      ['reports.view', 'full'],
      ['teams.view', 'full'],
      ['teams.manage', 'full'],
      ['users.view', 'full'],
      ['users.manage', 'full'],
      ['roles.view', 'full'],
      ['roles.manage', 'full'],
      ['settings.view', 'full'],
      ['settings.manage', 'full'],
      ['billing.view', 'full'],
      ['audit.view', 'full'],
      ['developer.manage', 'full'],
      ['profile.manage', 'full'],
    ]),
    system: true,
    memberCount: 0,
  },
  {
    id: 'role-supervisor',
    name: 'Supervisor',
    description: 'Manages agents, queues, flows and campaigns. No WhatsApp or billing rights.',
    scope: 'client',
    menus: [
      'dashboard',
      'inbox',
      'contacts',
      'flows',
      'templates',
      'campaigns',
      'reports',
      'teams',
      'users',
      'quickReplies',
      'profile',
    ],
    capabilities: capabilities([
      ['dashboard.view', 'full'],
      ['inbox.view', 'full'],
      ['inbox.reply', 'full'],
      ['inbox.assign', 'full'],
      ['contacts.view', 'full'],
      ['contacts.manage', 'full'],
      ['contacts.export', 'view'],
      ['flows.view', 'full'],
      ['flows.manage', 'full'],
      ['templates.view', 'full'],
      ['templates.manage', 'full'],
      ['campaigns.view', 'full'],
      ['campaigns.manage', 'full'],
      ['reports.view', 'full'],
      ['teams.view', 'full'],
      ['teams.manage', 'full'],
      ['users.view', 'full'],
      ['users.manage', 'edit'],
      ['roles.view', 'view'],
      ['settings.view', 'view'],
      ['developer.manage', 'view'],
      ['profile.manage', 'full'],
    ]),
    system: true,
    memberCount: 0,
  },
  {
    id: 'role-agent',
    name: 'Support Agent',
    description: 'Works assigned conversations only. No access to automation settings or exports.',
    scope: 'client',
    menus: ['dashboard', 'inbox', 'contacts', 'profile'],
    capabilities: capabilities([
      ['dashboard.view', 'view'],
      ['inbox.view', 'full'],
      ['inbox.reply', 'full'],
      ['inbox.assign', 'view'],
      ['contacts.view', 'view'],
      ['flows.view', 'view'],
      ['templates.view', 'view'],
      ['profile.manage', 'edit'],
    ]),
    system: true,
    memberCount: 0,
  },
  {
    id: 'role-developer',
    name: 'Integration User',
    description:
      'Builds on the workspace APIs: Developer Hub and read-only settings. No inbox, staff or billing access.',
    scope: 'client',
    menus: ['dashboard', 'developer', 'settings', 'profile'],
    capabilities: capabilities([
      ['dashboard.view', 'view'],
      ['developer.manage', 'full'],
      ['settings.view', 'view'],
      ['profile.manage', 'full'],
    ]),
    system: true,
    memberCount: 0,
  },
  {
    id: 'role-platform-owner',
    name: 'Platform Owner',
    description: 'Manages plans, provisioning, Meta configuration and platform health.',
    scope: 'platform',
    menus: PLATFORM_ALL_MENUS,
    capabilities: capabilities([
      ['dashboard.view', 'full'],
      ['clients.view', 'full'],
      ['clients.manage', 'full'],
      ['plans.manage', 'full'],
      ['users.view', 'full'],
      ['users.manage', 'full'],
      ['roles.view', 'full'],
      ['roles.manage', 'full'],
      ['analytics.view', 'full'],
      ['meta.manage', 'full'],
      ['health.view', 'full'],
      ['announcements.manage', 'full'],
      ['audit.view', 'full'],
      ['profile.manage', 'full'],
      ['settings.manage', 'full'],
    ]),
    system: true,
    memberCount: 0,
  },
  {
    id: 'role-platform-operations',
    name: 'Platform Operations',
    description: 'Onboarding, support and tenant administration. No plan or Meta app changes.',
    scope: 'platform',
    menus: ['dashboard', 'clients', 'users', 'health', 'announcements', 'audit', 'profile'],
    capabilities: capabilities([
      ['dashboard.view', 'full'],
      ['clients.view', 'full'],
      ['clients.manage', 'edit'],
      ['users.view', 'full'],
      ['users.manage', 'edit'],
      ['roles.view', 'view'],
      ['health.view', 'full'],
      ['announcements.manage', 'full'],
      ['audit.view', 'full'],
      ['profile.manage', 'full'],
    ]),
    system: true,
    memberCount: 0,
  },
];

/**
 * Plan → modules. Seeds `MockDataService.plans`; `/plans/matrix` edits the
 * live rows from there, and `PermissionService.planModules` reads them back.
 */
export const PLAN_MODULES: Record<string, MenuKey[]> = {
  Pilot: [
    'dashboard',
    'inbox',
    'contacts',
    'templates',
    'teams',
    'users',
    'roles',
    'quickReplies',
    'settings',
    'profile',
  ],
  Growth: [
    'dashboard',
    'inbox',
    'contacts',
    'flows',
    'templates',
    'campaigns',
    'reports',
    'teams',
    'users',
    'roles',
    'quickReplies',
    'settings',
    'billing',
    'audit',
    'profile',
  ],
  Scale: CLIENT_ALL_MENUS,
};

export const DEFAULT_PLAN_MODULES = PLAN_MODULES['Pilot']!;
